name: octal_clock_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  octal_clock: ^0.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true